server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: coupon
          uri: http://localhost:8081
          predicates:
            - Path=/coupons/**, 
        - id: point
          uri: http://localhost:8082
          predicates:
            - Path=/points/**, 
        - id: dashboard
          uri: http://localhost:8083
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: coupon
          uri: http://coupon:8080
          predicates:
            - Path=/coupons/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
